{
  if (!(exception ? throwable instanceof RuntimeException : throwable == null)) {
    throw new AssertionError();
  }
  exit++;
}
